//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishReaderApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DishReaderApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Reader.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISH READER.
        /// </summary>
        public static string AppTitleCapitalized {
            get {
                return ResourceManager.GetString("AppTitleCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Dapper Panda.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feedback.
        /// </summary>
        public static string ButtonFeedback {
            get {
                return ResourceManager.GetString("ButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string ButtonRate {
            get {
                return ResourceManager.GetString("ButtonRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Reader is a simple and fast reader for political blog The Dish by Andrew Sullivan..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not associated with The Dish, Daily Beast or Andrew Sullivan..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not hesitate to send any feedback or feature requests.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string PageTitleBlog {
            get {
                return ResourceManager.GetString("PageTitleBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate and comment on this app in Marketplace.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.dapperpanda.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
